### ISSUE TITLE
cursorSubword shortcuts not showing up in keyboard bindings list

### ISSUE THREAD

**Issue by jcairney** [ow--/vscode-subword-navigation#27]
VSCODE:
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Subword Navigation: v1.1.5

After installing the plugin and reloading VSCode I am not able to find any trace of the extension other than that it shows up as installed in the extensions area.  I find no related settings under Keyboard Shortcuts or Settings...

**Comment by ow--** [comment]
Yes, you're right. I haven't looked into working with the new shortcut UI. That'll give me a good reason to update the project overall.

For now, open the old keyboard shortcuts file and add it manually according to the readme.

**Comment by jcairney** [comment]
Thanks! I'm new to configuring VSCode.  Could you give me a path to the keyboard shortcuts file?

**Comment by ow--** [comment]
Oh, no worries. Hit ctrl+shift+P (or cmd+shift+p on mac, I suppose) or F1 and type in keyboard and choose `Preferences: Open Keyboard Shortcut File`. Then you can add the shortcuts you're interested in in the right pane from the readme, or look up `cursorWordEndRight` in the left to see how the regular word navigation is set up. I personally keep the regular ones and add subword on alt+left/right etc.

**Comment by jcairney** [comment]
Also a case of RTFM.  The Details in VS Code for your plugin explains exactly what to do, and I have it working now.  But I agree that supporting the shortcut UI would benefit other hasty or illiterate users like me. 

Strangely, after adding the key bindings in keybindings.json, and then commenting them out, the related commands remain visible in the Shortcuts UI where I couldn't find them before.  They are not labelled though.

**Comment by ow--** [comment]
Yeah, so I just assumed they show up automatically and didn't think better of it.

**Comment by kumarharsh** [comment]
Ah, good thing I checked here! I thought the plugin was broken and was going to be very angry/depressed 😜

**Comment by ow--** [comment]
Well, I can't figure out how to contribute an unassigned keybinding. It seems to only be possible with lower level command registration than what the extension API allows for.

I suppose I could just use my own preferences, which incidentally is also what Sublime uses, for Windows/Linux and follow Xcode (and Sublime?) for macOS, but I'm a bit hesitant to since they override several vscode defaults and Mission Control has usurped `ctrl+left/right`.

Decisions, decisions...

**Comment by kumarharsh** [comment]
Yeah, it seems so.

Maybe you can specify different bindings for Mac? See here: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeskeybindings

**Comment by inosik** [comment]
It looks like the extensions needs to be activated, before the commands become available in the keybindings UI. Default keybindings just work around this, because VS Code then activates the extension on startup.

Changing `activationEvents` to `["*"]` should make VS Code activate the extension on startup.

**Comment by ow--** [comment]
Ohh, nice find! Might reconsider this then. Especially if the defaults doesn't fare well.
